[workspace]
authors = ["Quentin Febvre <quentin.febvre@imt-atlantique.fr>"]
channels = ["conda-forge"]
name = "naga"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "pytest" }

[feature.test.dependencies]
pytest = ">=8.3.2,<9"
pytest-mock = ">=3.14.0,<4"

[dependencies]
xxhash = ">=0.8.3,<0.9"
python = "3.11.*"
dvc = ">=3.63.0,<4"
omegaconf = ">=2.3.0,<3"
gitpython = ">=3.1.45,<4"
python-xxhash = ">=3.5.0,<4"
mlflow = ">=3.2.0,<4"
joblib = ">=1.5.2,<2"
pandas = ">=2.3.2,<3"
submitit = ">=1.5.2,<2"

[pypi-dependencies]
xxhash = ">=3.5.0, <4"
dirhash = ">=0.5.0, <0.6"

[environments]
test = { features = ["test"], solve-group = "test" }
